version: '3.1'

services:
  api:
    image: twitter-feed:latest
    build: .
    networks:
      - test-twitter-feed
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://root@roach1:26257/defaultdb?sslmode=disable"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
    command: "/twitter-feed api"
    depends_on:
      - rabbitmq
      - roach1
  sse:
    image: twitter-feed:latest
    networks:
      - test-twitter-feed
    ports:
      - 3001:3000
    environment:
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
    command: "/twitter-feed sse"
    depends_on:
      - rabbitmq
  bot:
    image: twitter-feed:latest
    networks:
      - test-twitter-feed
    environment:
      API_BASE_PATH: "http://api:3000/api"
    command: "/twitter-feed bot --delay=15 --reqs-per-min=12"
    depends_on:
      - api
      - roach1
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - test-twitter-feed
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 5
  roach1:
    image: cockroachdb/cockroach:v23.1.3
    networks:
      - test-twitter-feed
    volumes:
      - roach1:/cockroach/cockroach-data
    ports:
      - 26257:26257
      - 8080:8080
    command: start --advertise-addr=roach1:26357 --http-addr=roach1:8080 --listen-addr=roach1:26357 --sql-addr=roach1:26257 --insecure --join=roach1:26357,roach2:26357
  roach2:
    image: cockroachdb/cockroach:v23.1.3
    depends_on:
      - roach1
    networks:
      - test-twitter-feed
    volumes:
      - roach2:/cockroach/cockroach-data
    ports:
      - 26258:26258
      - 8081:8081
    command: start --advertise-addr=roach2:26357 --http-addr=roach2:8081 --listen-addr=roach2:26357 --sql-addr=roach2:26258 --insecure --join=roach1:26357,roach2:26357

networks:
  test-twitter-feed:
    name: roachnet
    external: true
volumes:
  roach1: 
  roach2: