version: '3.1'

services:
  api:
    image: twitter-feed:latest
    build: .
    networks:
      - test-twitter-feed
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://root@roach1:26257/defaultdb?sslmode=disable"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
    command: "/twitter-feed api"
    depends_on:
      - rabbitmq
  sse:
    image: twitter-feed:latest
    networks:
      - test-twitter-feed
    ports:
      - 3001:3000
    environment:
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
    command: "/twitter-feed sse"
    depends_on:
      - rabbitmq
  bot:
    image: twitter-feed:latest
    networks:
      - test-twitter-feed
    environment:
      API_BASE_PATH: "http://api:3000/api"
    command: "/twitter-feed bot --delay=15 --reqs=10"
    depends_on:
      - rabbitmq
      - api
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - test-twitter-feed
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 5
networks:
  test-twitter-feed:
    name: roachnet
    external: true