name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Lint staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.3"
        install-go: false
    
    - name: Lint errcheck
      run: errcheck -exclude errcheck_excludes.txt ./...
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
